In [3]:
import pandas as pd
df=pd.read_csv('score.csv')

In [15]:
import pandas as pd
df=pd.read_csv('score.csv')
print(df)

    MathScore  Reading_Score  Reading_Score.1  Placement_Score  Club_Join_Date
0          74             89               63               92            2020
1          75             94               64               75            2018
2          74             94               60               78            2018
3          78             84               65               77            2020
4          74             87               79               92            2019
5          78             87               74               76            2018
6          66             94               67               86            2018
7          64             92               70               89            2021
8          69             94               62               86            2018
9          64             77               68               90            2019
10         69             89               70               98            2019
11         72             78               73               84            2021
12         68             91               62               90            2021
13         65             78               68               92            2018
14         80             95               76               79            2019
15         63             83               74               86            2020
16         66             89               77               81            2020
17         73             77               68               96            2018
18         79             92               70               76            2018
19         80             89               80               80            2020
20         60             93               77               81            2021
21         62             83               78               96            2018
22         71             81               66               76            2019
23         66             88               75               93            2019
24         76             79               67               78            2019
25         74             90               60              100            2019
26         60             75               66               75            2019
27         68             80               62               75            2020
28         75             80               79               87            2021
29         60             80               79               86            2020
30         74             90               68               84            2020
31         79             86               60               84            2020
32         71             76               63               90            2019
33         66             88               68               84            2021
34         75             88               71               93            2021
35         79             85               78               94            2021
36         80             83               73               94            2019
37         71             89               77               76            2020
38         67             76               72               78            2021
39         65             75               78               99            2018
40         68             88               75               80            2020
41         69             94               60               81            2020
42         74             89               62               96            2020
43         68             84               78               87            2019
44         63             81               67               93            2021
45         76             83               60               85            2020
46         75             77               69               81            2021
47         66             81               80               99            2021
48         80             82               60               81            2019

In [17]:
df.isnull()

    MathScore  Reading_Score  Reading_Score.1  Placement_Score  Club_Join_Date
0       False          False            False            False           False
1       False          False            False            False           False
2       False          False            False            False           False
3       False          False            False            False           False
4       False          False            False            False           False
5       False          False            False            False           False
6       False          False            False            False           False
7       False          False            False            False           False
8       False          False            False            False           False
9       False          False            False            False           False
10      False          False            False            False           False
11      False          False            False            False           False
12      False          False            False            False           False
13      False          False            False            False           False
14      False          False            False            False           False
15      False          False            False            False           False
16      False          False            False            False           False
17      False          False            False            False           False
18      False          False            False            False           False
19      False          False            False            False           False
20      False          False            False            False           False
21      False          False            False            False           False
22      False          False            False            False           False
23      False          False            False            False           False
24      False          False            False            False           False
25      False          False            False            False           False
26      False          False            False            False           False
27      False          False            False            False           False
28      False          False            False            False           False
29      False          False            False            False           False
30      False          False            False            False           False
31      False          False            False            False           False
32      False          False            False            False           False
33      False          False            False            False           False
34      False          False            False            False           False
35      False          False            False            False           False
36      False          False            False            False           False
37      False          False            False            False           False
38      False          False            False            False           False
39      False          False            False            False           False
40      False          False            False            False           False
41      False          False            False            False           False
42      False          False            False            False           False
43      False          False            False            False           False
44      False          False            False            False           False
45      False          False            False            False           False
46      False          False            False            False           False
47      False          False            False            False           False
48      False          False            False            False           False

In [21]:
series=pd.isnull(df["MathScore"])
df[series]

Empty DataFrame
Columns: [MathScore, Reading_Score, Reading_Score.1, Placement_Score, Club_Join_Date]
Index: []

In [23]:
series=pd.isnull(df["MathScore"])
df[series]

Empty DataFrame
Columns: [MathScore, Reading_Score, Reading_Score.1, Placement_Score, Club_Join_Date]
Index: []

In [25]:
df.isnull()

    MathScore  Reading_Score  Reading_Score.1  Placement_Score  Club_Join_Date
0       False          False            False            False           False
1       False          False            False            False           False
2       False          False            False            False           False
3       False          False            False            False           False
4       False          False            False            False           False
5       False          False            False            False           False
6       False          False            False            False           False
7       False          False            False            False           False
8       False          False            False            False           False
9       False          False            False            False           False
10      False          False            False            False           False
11      False          False            False            False           False
12      False          False            False            False           False
13      False          False            False            False           False
14      False          False            False            False           False
15      False          False            False            False           False
16      False          False            False            False           False
17      False          False            False            False           False
18      False          False            False            False           False
19      False          False            False            False           False
20      False          False            False            False           False
21      False          False            False            False           False
22      False          False            False            False           False
23      False          False            False            False           False
24      False          False            False            False           False
25      False          False            False            False           False
26      False          False            False            False           False
27      False          False            False            False           False
28      False          False            False            False           False
29      False          False            False            False           False
30      False          False            False            False           False
31      False          False            False            False           False
32      False          False            False            False           False
33      False          False            False            False           False
34      False          False            False            False           False
35      False          False            False            False           False
36      False          False            False            False           False
37      False          False            False            False           False
38      False          False            False            False           False
39      False          False            False            False           False
40      False          False            False            False           False
41      False          False            False            False           False
42      False          False            False            False           False
43      False          False            False            False           False
44      False          False            False            False           False
45      False          False            False            False           False
46      False          False            False            False           False
47      False          False            False            False           False
48      False          False            False            False           False

In [37]:
import pandas as pd
df=pd.read_csv('score.csv')
df

    MathScore  Reading_Score  Reading_Score.1  Placement_Score  Club_Join_Date
0         NaN             87               61               83            2020
1        72.0             76               72               91            2020
2        63.0             83               75               77            2018
3        60.0             86               63               97            2020
4        65.0             85               62               98            2019
5        79.0             86               69               98            2018
6        70.0             79               71               75            2020
7        63.0             80               72               79            2020
8        79.0             82               70               99            2018
9        65.0             94               63               80            2021
10       61.0             77               70               78            2019
11       77.0             78               77               81            2019
12       79.0             91               70               87            2021
13       69.0             81               75               85            2021
14       66.0             95               63               87            2018
15       61.0             90               62               80            2021
16       69.0             92               67               86            2020
17       78.0             85               69               76            2021
18       69.0             95               67               77            2020
19       65.0             86               64               86            2018
20       64.0             89               72               89            2019
21       69.0             82               70               90            2020
22       72.0             79               79               95            2021
23       78.0             83               61               75            2021
24       75.0             80               63               93            2020
25       63.0             80               69               80            2019
26       65.0             89               63               94            2018
27       68.0             92               60               98            2020
28       78.0             80               74               98            2021
29       63.0             93               66               77            2018
30       60.0             88               68               84            2019
31       76.0             81               73              100            2018
32       78.0             93               63               78            2018
33       77.0             87               73               81            2020
34       62.0             84               75               81            2018
35       68.0             93               80               82            2021
36       72.0             95               61               77            2021
37       61.0             95               80               79            2021
38       73.0             78               74               93            2019
39       77.0             76               73               97            2019
40       68.0             80               80               91            2021
41       71.0             93               64               83            2018
42       71.0             84               78               93            2021
43       65.0             92               63               78            2018
44       79.0             90               67               81            2020
45       80.0             89               69               93            2018
46       64.0             83               62               79            2020
47       62.0             91               72               78            2019
48       65.0             80               77               81            2019

In [39]:
df.isnull()

    MathScore  Reading_Score  Reading_Score.1  Placement_Score  Club_Join_Date
0        True          False            False            False           False
1       False          False            False            False           False
2       False          False            False            False           False
3       False          False            False            False           False
4       False          False            False            False           False
5       False          False            False            False           False
6       False          False            False            False           False
7       False          False            False            False           False
8       False          False            False            False           False
9       False          False            False            False           False
10      False          False            False            False           False
11      False          False            False            False           False
12      False          False            False            False           False
13      False          False            False            False           False
14      False          False            False            False           False
15      False          False            False            False           False
16      False          False            False            False           False
17      False          False            False            False           False
18      False          False            False            False           False
19      False          False            False            False           False
20      False          False            False            False           False
21      False          False            False            False           False
22      False          False            False            False           False
23      False          False            False            False           False
24      False          False            False            False           False
25      False          False            False            False           False
26      False          False            False            False           False
27      False          False            False            False           False
28      False          False            False            False           False
29      False          False            False            False           False
30      False          False            False            False           False
31      False          False            False            False           False
32      False          False            False            False           False
33      False          False            False            False           False
34      False          False            False            False           False
35      False          False            False            False           False
36      False          False            False            False           False
37      False          False            False            False           False
38      False          False            False            False           False
39      False          False            False            False           False
40      False          False            False            False           False
41      False          False            False            False           False
42      False          False            False            False           False
43      False          False            False            False           False
44      False          False            False            False           False
45      False          False            False            False           False
46      False          False            False            False           False
47      False          False            False            False           False
48      False          False            False            False           False

In [41]:
series=pd.isnull(df["MathScore"])
df[series]

   MathScore  Reading_Score  Reading_Score.1  Placement_Score  Club_Join_Date
0        NaN             87               61               83            2020

In [43]:
import pandas as pd
df=pd.read_csv('score.csv')
df

,MathScore,Reading_Score,Reading_Score.1,Placement_Score,Club_Join_Date,Gender
0,NaN,83,62,87,2019,1
1,71.0,82,67,91,2020,1
2,68.0,77,63,79,2019,1
3,61.0,80,60,80,2018,1
4,74.0,77,71,96,2021,1
5,74.0,86,76,85,2020,1
6,66.0,89,60,80,2020,0
7,76.0,76,71,96,2019,1
8,71.0,80,79,91,2019,0
9,77.0,95,79,91,2020,0
10,79.0,75,80,91,2018,0
11,61.0,77,60,88,2020,1
12,75.0,81,63,91,2019,1
13,64.0,84,63,79,2020,1
14,70.0,88,64,88,2018,0
15,64.0,77,70,92,2019,0
16,73.0,81,79,89,2020,1
17,69.0,78,62,86,2018,1
18,74.0,87,66,88,2018,0
19,65.0,88,63,99,2021,1
20,71.0,85,75,81,2019,0
21,76.0,90,79,86,2018,0
22,69.0,93,72,99,2018,1
23,79.0,77,68,96,2021,1
24,77.0,75,69,79,2021,0
25,63.0,87,80,75,2020,1
26,60.0,93,80,95,2020,0
27,67.0,92,75,83,2018,1
28,72.0,92,71,95,2018,1
29,76.0,82,72,93,2020,1
30,74.0,77,70,98,2020,0
31,71.0,89,66,86,2020,0
32,63.0,88,75,84,2021,0
33,75.0,92,61,78,2019,0
34,72.0,82,77,100,2021,0
35,67.0,83,73,93,2018,1
36,71.0,76,74,98,2018,0
37,61.0,75,76,83,2018,1
38,70.0,90,74,75,2018,0
39,71.0,93,80,75,2019,1
40,69.0,80,67,83,2018,0
41,67.0,86,63,92,2019,0
42,64.0,82,68,88,2018,1
43,78.0,80,67,95,2019,1
44,78.0,91,78,77,2021,0
45,76.0,78,63,94,2019,1
46,76.0,82,69,77,2020,1
47,71.0,87,67,80,2019,0
48,74.0,81,70,90,2020,0

In [45]:
m_v=df['math score'].mean()
df['math score'].fillna(value=m_v, inplace=True)
df

KeyError: 'math score'

In [47]:

math_score_mean = df.get('math score', pd.Series()).mean()


if not math_score_mean.isna():
    df['math score'].fillna(value=math_score_mean, inplace=True)
else:
    print("'math score' column is missing.")

AttributeError: 'float' object has no attribute 'isna'